name: critical-period
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - tqdm
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pylint
  - pip
  - pip:
    - ipdb
