program: ./src/learn/train_gpt2.sh
project: critical-period
method: bayes
metric:
  goal: minimize
  name: eval_loss
parameters:
  gradient_accumulation_steps:
    values: [16, 32, 64, 128, 256]
  learning_rate:
    distribution: log_uniform_values
    min: 10e-5
    max: 10e-2
  warmup_ratio:
    values: [0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
early_terminate:
  type: hyperband
  min_iter: 5
  eta: 2
command:
  - ${env}
  - bash
  - ${program}
  - ${args}
