program: ./src/learn/train_roberta.sh
project: critical-period
method: bayes
metric:
  goal: minimize
  name: eval_loss
parameters:
  gradient_accumulation_steps:
    values: [16,32,64]
  learning_rate:
    min: 0.0001
    max: 0.1
  mlm_probability:
    values: [0.15, 0.4]
  warmup_ratio:
    values: [0.06]
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
command:
  - ${env}
  - "DATA_DIR='data/${DATASET}/${LANG1}'"
  - "MODEL_NAME='${MODEL}-${LANG1}-${SEED}-${DATE}'"
  - bash
  - ${program}
  - "--max_eval_samples 100"
  - "--max_train_samples 100"
  - ${args}
